# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "create-subscription"
client_id = "52729dd82cabe6d1dc0b218e40e31369"
application_url = "https://955c-2401-4900-1cb5-e183-44a9-9de3-ae8a-32d8.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://955c-2401-4900-1cb5-e183-44a9-9de3-ae8a-32d8.ngrok-free.app/auth/callback",
  "https://955c-2401-4900-1cb5-e183-44a9-9de3-ae8a-32d8.ngrok-free.app/auth/shopify/callback",
  "https://955c-2401-4900-1cb5-e183-44a9-9de3-ae8a-32d8.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "divyatestapp.myshopify.com"
